<?php
/***************************************************************** 
**  Guest Access									**
**  Autor: Thor2705												**
**  Copyright © 2007 Thor2705, e.ignea [at] edidesign [dot] ro  **
**	Please read the License file that came with this package	**
**	If you got this file without having a license file in the	**
**	please contact the owner at the above email or				**
**	vist http://www.ignea.ro/license.php for the latest one		**
*****************************************************************/

if(!defined("IN_MYBB")) {
    die("This file cannot be accessed directly.");
}

$plugins->add_hook("showthread_start", "guestaccess");


function guestaccess_info()
{
	return array(
		'name'			=> 'Guest Access',
		'description'	=> 'Allows you to set the number of threads that can be read by guests',
		'website'		=> 'http://edidesign.ro',
		'author'		=> 'Thor2705',
		'authorsite'	=> 'http://edidesign.ro',
		'version'		=> '2.0',
	);
}

function guestaccess_activate() {
   global $db;
   	$guestaccess_group = array(
		"gid"			=> "NULL",
		"name"			=> "guestaccess",
		"title"			=> "Guest Access",
		"description"	=> "Thread Viewing Limits For Guests",
		"disporder"		=>"1",
		"isdefault"		=> "no",
	);

	$db->insert_query("settinggroups", $guestaccess_group);
	$gid = $db->insert_id();


	$guestaccess_setting_1 = array(
		"sid"			=> "NULL",
		"name"			=> "enableguestaccess",
		"title"			=> "Enable Guest Access",
		"description"	=> "If set to off, Guests will have no limits placed on them",
		"optionscode"	=> "onoff",
		"value"			=> "on",
		"disporder"		=> 1,
		"gid"			=> intval($gid),
	);
	
	$guestaccess_setting_2 = array(
		"sid"			=> "NULL",
		"name"			=> "guestspostview",
		"title"			=> "How many posts can guests view?",
		"description"	=> "How many posts can the guest view before they get a the message set below?",
		"optionscode"	=> "text",
		"value"			=> "5",
		"disporder"		=> 2,
		"gid"			=> intval($gid),
	);
	$guestaccess_setting_3 = array(
		"sid"			=> "NULL",
		"name"			=> "guestsmessageaccess",
		"title"			=> "Message To Show Guests",
		"description"	=> "What message will they see when they have reached their limit?",
		"optionscode"	=> "textarea",
		"value"			=> 'To View More Threads please <a href="member.php?action=login">Login</a> Or <a href="member.php?action=register">Register</a> Thank you.',
		"disporder"		=> 3,
		"gid"			=> intval($gid),
	);
	$db->insert_query("settings", $guestaccess_setting_1);
	$db->insert_query("settings", $guestaccess_setting_2);
	$db->insert_query("settings", $guestaccess_setting_3);
	rebuild_settings();
	
}
function guestaccess_deactivate() {
	global $db;
	$db->delete_query("settinggroups WHERE name='guestaccess'");
	$db->delete_query("settings WHERE name IN (
	'guestspostview',
	'enableguestaccess',
	'guestsmessageaccess')
	");
	rebuild_settings();
}

function guestaccess() {
	global $mybb,$db;
	if ($mybb->user['uid'] == "")
	{
	if ($mybb->settings['enableguestaccess'] == "1")
	{
	if ($_COOKIE['threadsviewed'] == "")
	{
	my_setcookie("threadsviewed", "1", null, true);
	return;
	}
	else {
		if ($mybb->settings['guestspostview'] <= $_COOKIE['threadsviewed'])
		{
			error($mybb->settings['guestsmessageaccess']);
		}
		else {
			$old=$_COOKIE['threadsviewed'];
			$new=$old+1;
			my_setcookie("threadsviewed", "$new", null, true);
		}
	}
	}
	}

}

if(!function_exists("rebuild_settings")) {

	function rebuild_settings() {
		global $db;
		$query = $db->query("SELECT * FROM ".TABLE_PREFIX."settings ORDER BY title ASC");
		while($setting = $db->fetch_array($query)) {
			$setting['value'] = addslashes($setting['value']);
			$settings .= "\$settings['".$setting['name']."'] = \"".$setting['value']."\";\n";
		}
		$settings = "<?php\n/*********************************\ \n  DO NOT EDIT THIS FILE, PLEASE USE\n  THE SETTINGS EDITOR\n\*********************************/\n\n$settings\n?>";
		$file = fopen(MYBB_ROOT."/inc/settings.php", "w");
		fwrite($file, $settings);
		fclose($file);
	}
}
?>